# Generated by Django 3.2.6 on 2021-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210815_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
