# Generated by Django 3.2.6 on 2021-08-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210818_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
