# Generated by Django 3.2.6 on 2021-08-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_wishlist_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_id',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product', serialize=False, to='company.product'),
        ),
    ]
